apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: bitnami/nginx
    spec:
      containers:
        - image: bitnami/nginx
          name: nginx
          ports:
            - containerPort: 80
